# Change these first
owner: authentiqdigital # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Authentiq
    url: https://www.authentiq.ch
  - name: Contact Tracing
    url: https://ct.authentiq.ch
  - name: Helpp Admin
    url: https://admin.helpp-app.ch
assignees:
  - ndersh
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /uptime
  name: Status
  introTitle: "**Status**"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
